auf/auf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('rest_api.urls')),
    path('cart/', include('cart.urls')),
    path('', include('board.urls')),
    path('queryset/', include('queryset.urls')),

]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auf/rest_api/urls.py
from django.urls import path

from .views import hola_api, hola2, hola3, relation, relation2, producer_detail, production_detail

app_name = 'rest_api'

urlpatterns = [
    path('hola/', hola_api, name='hola'),
    path('hola2/', hola2, name='hola2'),
    path('hola3/', hola3, name='hola3'),
    path('relation/', relation, name='relation'),
    path('relation2/', relation2, name='relation2'),
    path('producer_detail/<int:id>', producer_detail, name='producer_detail'),
    path('production_detail/<int:id>', production_detail, name='production_detail'),
]

auf/rest_api/models.py
from django.db import models

class BBooks(models.Model):
    title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    year = models.IntegerField(default=20)

    def __str__(self):
        return self.title


class Album(models.Model):
    album_name = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)

class Track(models.Model):
    album = models.ForeignKey(Album, related_name='tracks', on_delete=models.CASCADE)
    order = models.IntegerField()
    title = models.CharField(max_length=100)
    duration = models.IntegerField()

    class Meta:
        unique_together = ['album', 'order']
        ordering = ['order']

    def __str__(self):
        return '%d: %s' % (self.order, self.title)

class Pep(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name

class Experience(models.Model):
    title = models.ForeignKey(Pep, related_name='pep', on_delete=models.CASCADE)
    organization = models.CharField(max_length=100)
    duration = models.IntegerField()

    # class Meta:
    #     unique_together = ['first_name']

    def __str__(self):
        return self.organization

# Selected_related and prtfecrure_related
class Producer(models.Model):
    title = models.CharField(max_length=200)
    productions = models.ManyToManyField('Production', related_name='productions', blank=True)

    def __str__(self):
        return self.title

class Production(models.Model):
    title = models.CharField(max_length=200)
    producers = models.ManyToManyField('Producer', related_name='producers', blank=True,default='Unknown')

    def __str__(self):
        return self.title

auf/rest_api/views.py
from django.http import JsonResponse
from django.shortcuts import render
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .models import BBooks, Album, Pep, Producer, Production
from .serializers import BBooksSerializers, AlbumSerializer, PepSerializer, ProducersSerializer, ProductionsSerializer


# @api_view(['GET'])
# def hola_api(request):
#     if request.method == 'GET':
#         b = BBooks.objects.all()
#         serializer = BBooksSerializers(b, many=True)
#         return Response(serializer.data)

@api_view(['GET', 'POST'])
def hola_api(request):
    # books = BBooks.objects.all()
    # serializer = BBooksSerializers(books, many=True)



    if request.method == 'GET':
        bbooks = BBooks.objects.all()
        serializer = BBooksSerializers(bbooks, many=True)
        return Response(serializer.data)

    if request.method == 'POST':
        print('REQUEST.DATA', request.data)
        bbooks = request.data
        title=request.data.get('title')
        genre=request.data.get('genre')
        year=request.data.get('year')
        print('TITLE DATA', title)
        print('GENRE DATA', genre)
        print('YEAR DATA', year)
        serr=BBooksSerializers(data=bbooks)

        if serr.is_valid():
            serr.save()
            return Response({'Success': ' created succesfully'})
        else:
            return Response({'Error':'Errorrrr'})
    # return Response(serializer2.data)

@api_view(['GET', 'POST'])
def hola2(request):
        # books = BBooks.objects.all()
        # serializer = BBooksSerializers(books, many=True)

    if request.method == 'GET':
        album = Album.objects.all()
        serializer = AlbumSerializer(album, many=True)
        return Response(serializer.data)

    if request.method == 'POST':
        album = request.data
        serr = BBooksSerializers(data=album)

        if serr.is_valid():
            serr.save()
            return Response({'Success': ' created succesfully'})
        else:
            return Response({'Error': 'Errorrrr'})
@api_view(['GET', 'POST'])
def hola3(request):
        # books = BBooks.objects.all()
        # serializer = BBooksSerializers(books, many=True)

    if request.method == 'GET':
        pep = Pep.objects.all()
        serializer = PepSerializer(pep, many=True)
        return Response(serializer.data)

    if request.method == 'POST':
        pep = request.data
        serr = PepSerializer(data=pep)

        if serr.is_valid():
            serr.save()
            return Response({'Success': ' created succesfully'})
        else:
            return Response({'Error': 'Errorrrr'})


def relation(request):
    producers = Producer.objects.all()
    print(producers)
    for producer in producers:
        prod = producer.productions.all()
        # print(prod, producer)
    productions = Production.objects.all()
    print(productions)
    context = {'producers': producers, 'productions': productions}
    return render(request, 'relation.html', context)

@api_view(['GET'])
def relation2(request):
    producers = Producer.objects.all()
    productions = Production.objects.all()
    serializer1 = ProducersSerializer(producers, many=True)
    serializer2 = ProductionsSerializer(productions, many=True)
    return Response(serializer2.data)

def producer_detail(request, id):
    producer = Producer.objects.get(id=id)
    p = producer.producers.all()
    context = {'products': p, 'producer': producer}
    return render(request, 'producer_detail.html', context)

def production_detail(request, id):
    product = Production.objects.get(id=id)
    p = product.productions.all()
    context = {'producers': p, 'product': product}
    return render(request, 'production_detail.html', context)

auf/rest_api/templates/producer_detail.html
{% extends 'main_page.html' %}
{% block page_name %}
<h1>{{producer.title}}</h1>
{% endblock %}
{% block content %}
<table class="table table-bordered">
  <tr>
    <td>Продукты производства</td>
  </tr>

  <tr>

    <td>
     <table class="table table-bordered">
       <tr>
         <td>id</td>
         <td>Production</td>
       </tr>
       {% for product in products %}
       <tr>
         <td>{{product.id}}</td>
         <td>{{product.title}}</td>
       </tr>
       {% endfor %}
     </table>
    </td>
  </tr>
</table>
{% endblock %}

auf/rest_api/templates/production_detail.html
{% extends 'main_page.html' %}
{% block page_name %}
<h1>{{product.title}}</h1>
{% endblock %}
{% block content %}
<table class="table table-bordered">
  <tr>
    <td>Страны производители</td>
  </tr>

  <tr>

    <td>
     <table class="table table-bordered">
       <tr>
         <td>id</td>
         <td>Producers</td>
       </tr>
       {% for producer in producers %}
       <tr>
         <td>{{producer.id}}</td>
         <td>{{producer.title}}</td>
       </tr>
       {% endfor %}
     </table>
    </td>
  </tr>
</table>
{% endblock %}

auf/rest_api/templates/relation.html
{% extends 'main_page.html' %}
{% block page_name %}
<h1>Таблица взаимосвязей</h1>
{% endblock %}
{% block content %}
<table class="table table-bordered">
  <tr>
    <td>Производитель</td>
    <td>Продукты производства</td>
  </tr>

  <tr>
     <td>
     <table class="table table-bordered">
       <tr>
         <td>id</td>
         <td>Название</td>
       </tr>
       {% for producer in producers %}
       <tr>
         <td><a href="{% url 'rest_api:producer_detail' producer.id%}">{{producer.id}}</a></td>
         <td><a href="{% url 'rest_api:producer_detail' producer.id%}">{{producer.title}}</a></td>
       </tr>
       {% endfor %}
     </table>
    </td>
    <td>
     <table class="table table-bordered">
       <tr>
         <td>id</td>
         <td>Production</td>
       </tr>
       {% for product in productions %}
       <tr>
         <td><a href="{% url 'rest_api:production_detail' product.id %}">{{product.id}}</a></td>
         <td><a href="{% url 'rest_api:production_detail' product.id %}">{{product.title}}</a></td>
       </tr>
       {% endfor %}
     </table>
    </td>
  </tr>
</table>
{% endblock %}