auf/auf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('rest_api.urls')),
    path('cart/', include('cart.urls')),
    path('', include('board.urls')),
    path('queryset/', include('queryset.urls')),

]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auf/board/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from .views import index, AddBookView, author_add, year_add, genre_add, detail, authors, genres, search, author_detail, \
    genre_detail

urlpatterns = [
    path('', index, name='index'),
    path('main_page/', index, name='main_page'),
    path('add/', AddBookView.as_view(), name='add'),
    path('add_author/', author_add, name='add_author'),
    path('add_year/', year_add, name='add_year'),
    path('add_genre/', genre_add, name='add_genre'),
    path('detail/<int:book_id>', detail, name='detail'),
    path('author/<str:author_id>', author_detail, name='author_detail'),
    path('genres/<str:genre_id>', genre_detail, name='genre_detail'),
    path('authors/', authors, name='authors'),
    path('genres/', genres, name='genres'),
    path('search/', search, name='search'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
]

auf/search/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import search

urlpatterns = [
    path('', search, name = 'search' ),
]

auf/board/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from datetime import date


class Books(models.Model):
    title = models.CharField(max_length=100)
    genre = models.ForeignKey('Genre', on_delete=models.PROTECT)
    year = models.ForeignKey('Year', on_delete=models.PROTECT)
    author = models.ForeignKey('Author', on_delete=models.PROTECT)
    created = models.DateField(auto_now_add=True)
    description = models.TextField(max_length=1000)
    img = models.ImageField(upload_to='images', blank=True)
    price = models.DecimalField(max_digits=20, decimal_places=3)
    CONDITION = (
        ( 'Ough', '0'),
        ( 'Very bad', '1'),
        ( 'Bad', '2'),
        ( 'Normal', '3'),
        ( 'Not so bad', '4'),
        ( 'Like new', '5'),
    )
    condition = models.CharField(max_length=20, choices=CONDITION, default='3')
    price = models.IntegerField(default=100)
    quantitty = models.IntegerField(default=1)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail_view', args=[str(self.id)])

    class Meta:
        verbose_name = ' Экземпляр книги'
        verbose_name_plural = 'Книги'

class Genre(models.Model):
    genre = models.CharField(max_length=100)

    def __str__(self):
        return self.genre

    def get_absolut_url(self):
        return reverse('author_detail', args = [str(self.id)])

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Year(models.Model):
    year = models.CharField(max_length=100)

    def __str__(self):
        return self.year


class Author(models.Model):
    author = models.CharField(max_length=100)

    def __str__(self):
        return self.author

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4(), help_text='Уникальный ID для этого экземпляра книги из целой библиотеки')
    book = models.ForeignKey('Books', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'На обслуживании'),
        ('o', 'Взаймы'),
        ('a', 'Доступно'),
        ('r', 'Зарезервировано'),
    )
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Доступность книги')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)


    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return '%s (%s)' %(self.id, self.book.title)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

auf/search/models.py
from django.db import models

# Create your models here.

auf/board/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Books, Author, Genre, Year


class AddGenreForm(forms.ModelForm):
    genre = forms.CharField(max_length=100, label='Введите жанр')
    class Meta:
        model = Genre
        fields = '__all__'

class AddYearForm(forms.ModelForm):
    year = forms.CharField(max_length=100, label='Введите год')
    class Meta:
        model = Year
        fields = '__all__'

class AddAuthorForm(forms.ModelForm):
    author = forms.CharField(max_length=100, label='Введите автора')
    class Meta:
        model = Author
        fields = '__all__'

class AddItemForm(forms.ModelForm):
    class Meta:
        model = Books
        fields = '__all__'

    def clean(self):
        super().clean()
        errors = {}
        if not self.cleaned_data['description']:
            errors['description'] = ValidationError('Укажите описание')
        if self.cleaned_data['price'] < 0:
            errors['price'] = ValidationError('Укажите неотрицательное значение')

        if errors:
            raise ValidationError(errors)

class SearchForm(forms.Form):
    title = forms.CharField(max_length=100)

auf/search/forms.py
from django import forms
from wtforms import Form, StringField, SelectField

# class SearchForm(Form):
#     choices = [('title', 'Название'),
#     ('genre', 'Жанр'),
#     ('author', 'Автор'),
#     ('description', 'Описание') ,
#     ('price', 'Цена') ]
#     select = SelectField('Поиск книг по:', choices=choices)
#     search = StringField('')
#
# class SearchForm(forms.ModelForm):
#     title = forms.Charfield(max_length = 200)



class SearchForm(forms.ModelForm):
    title = forms.CharField(max_length=100, label='Название')

auf/board/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect, get_object_or_404
from django.template.defaultfilters import title
from django.urls import reverse_lazy
from django.views import generic
from django.views.decorators.http import require_POST
from django.views.generic import CreateView
from cart.forms import CartAddProductForm

from .forms import AddItemForm, AddAuthorForm, AddYearForm, AddGenreForm, SearchForm
from .models import Books, Author, Year, Genre, BookInstance



def index(request):
    books = Books.objects.all()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {'books': books, 'num_visits': num_visits}
    return render(request, 'main_page.html', context)

# def add_new(request):
#     if request.method == "POST":
#         form = AddItemForm(request.POST)
#         if form.is_valid():
#             book = form.cleaned_data
#             print(book)
#             book.save()
#     return render(request, 'main_page.html')

class AddBookView(CreateView):
    template_name = 'add_new.html'
    form_class = AddItemForm
    success_url = reverse_lazy('main_page')

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     # context['addnew'] = ['genre', 'year', 'author']
    #     print(context)
    #     return context

def year_add(request):
    year = Year.objects.all()
    form = AddYearForm(request.POST)
    if request.method == 'POST':
        form = AddYearForm(request.POST)
        if form.is_valid():
            a = form.cleaned_data['year']
            try:
                year = Year.objects.get(year__iexact=a)
                print('Введите заново')
                context = {'form': form}
                return render(request, 'add_year.html', context)
            except:
                form.save()
                return redirect('add')
    context = {'form': form}
    return render(request, 'add_year.html', context)

def author_add(request):
    author = Author.objects.all()
    form = AddAuthorForm(request.POST)
    if request.method == 'POST':
        form = AddAuthorForm(request.POST)
        if form.is_valid():
            a = form.cleaned_data['author']
            try:
                author = Author.objects.get(author__iexact=a)
                # if author:
                #     ValidationError('')
                # else:
                #     form.save()
                print('Введите заново')
                context = {'form': form}
                return render(request, 'add_author.html', context)
            except:
                form.save()
                return redirect('add')
    context = {'form': form}
    return render(request, 'add_author.html', context)

def genre_add(request):
    genre = Genre.objects.all()
    form = AddGenreForm(request.POST)
    if request.method == 'POST':
        form = AddGenreForm(request.POST)
        if form.is_valid():
            a = form.cleaned_data['genre']
            try:
                genre = Genre.objects.get(genre__iexact=a)
                print('Введите заново')
                context = {'form': form}
                return render(request, 'add_genre.html', context)
            except:
                form.save()
                return redirect('add')
    context = {'form': form}
    return render(request, 'add_genre.html', context)
# class AddAuthorView(CreateView):
#     template_name = 'add_author.html'
#     form_class = AddAuthorForm
#     success_url = reverse_lazy('add')
#
#     def get(self, request):
#         author = Author.objects.all()
#         print(author)
#         errors = {}
#         # if self.cleaned_data['author'] in author:
#         #     errors['author'] = ValidationError('Данный автор уже имеется')
def detail(request, book_id):
    print( request.POST,'4')
    book = get_object_or_404(Books, id = book_id)
    cart_product_form = CartAddProductForm(request.POST)
    # print(book,'12', book_id)
    return render(request, 'detail.html', {'book': book, 'cart_product_form': cart_product_form})

def author_detail(request, author_id):
    author = get_object_or_404(Author, id = author_id)
    books = Books.objects.filter(author_id=author_id)
    return render(request, 'author_detail.html', {'author': author, 'books': books})

def genre_detail(request, genre_id):
    genre = get_object_or_404(Genre, id = genre_id)
    books = Books.objects.filter(genre_id=genre_id)
    return render(request, 'genre_detail.html', {'genre': genre, 'books': books})

def authors(request):
    authors = Author.objects.all()
    return render(request, 'authors.html', {'authors': authors})

def genres(request):
    genres = Genre.objects.all()
    return render(request, 'genres.html', {'genres': genres})

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

def search(request):
    books = Books.objects.all()
    form = SearchForm()
    l = {}
    if request.method=='POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            f = form.cleaned_data
            f = f['title']
            for i in books:
                if f in i.title :
                    l[i] = i

    context = {'form': form, 'list': l}
    return render(request, 'search.html', context)

auf/search/views.py
from django.shortcuts import render
from flask import flash, render_template, request, redirect

# from ..models import Books
from .forms import SearchForm



    # books = Books.objects.all()
    # print(books)
    # form = SearchForm(request.POST)
    # if request.method == 'POST':
    #     form = SearchForm(request.POST)
    #     # return search_results(form)
    # return render(request, 'search.html', {'form':form})

auf/board/templates/add_author.html
{% extends 'main_page.html'%}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <ul>
        {{form.as_ul}}
    </ul>
    <button>Отправить</button>
</form>

{% endblock %}

auf/board/templates/add_genre.html
{% extends 'main_page.html'%}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <ul>
        {{form.as_ul}}
    </ul>
    <button>Отправить</button>
</form>

{% endblock %}

auf/board/templates/add_new.html
{% extends 'main_page.html'%}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <ul style="">
        <p>Название книги {{form.title}}</p>
        <p>Жанр {{form.genre}}<a href="/add_genre/">+</a> </p>
        <p>Год выпуска {{form.year}}<a href="/add_year/">+</a> </p>
        <p>Автор {{form.author}}<a href="/add_author/">+</a> </p>
        <p>Описание {{form.description}}</p>
        <p>Изображение обложки {{form.img}}</p>
        <p>Цена {{form.price}}</p>
        <p>Состояние {{form.condition}}</p>
    </ul>
<!--    {{form.title}}-->
    <button>Отправить</button>
</form>

{% endblock %}

auf/board/templates/add_year.html
{% extends 'main_page.html'%}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <ul>
        {{form.as_ul}}
    </ul>
    <button>Отправить</button>
</form>

{% endblock %}

auf/board/templates/author_detail.html
{% extends 'main_page.html'%}
{% block page_name %}
<h2>
    {{author.author}}
</h2>
{% endblock %}
{% block content %}
    <h1>{{author.author}}</h1>
{% for book in books %}
{{book.title}}
<img src="{{book.img.url}}" alt="" height="" >
{% endfor %}

{% endblock %}

auf/board/templates/authors.html
{% extends 'main_page.html'%}

{% block content %}
{% for author in authors %}

<a type="button" class="btn btn-light" href="{% url 'author_detail' author.id %}">{{author.author}}<br></a>

{% endfor %}

{% endblock %}

auf/board/templates/bookinstance_list_borrowed_user.html
  <!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>{% block title%}STORE{% endblock%}</title>

</head>
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <nav class="navbar navbar-expand bg-info navbar-dark navbar-fixed-top ">
                <a class="navbar-brand" href='/main_page/'}>Главная страница</a>
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="/authors/">Авторы</a>
                    </li>

                    <a class="nav-link" href="/genres/">Жанры</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/add/">Добавление книги</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/mybooks/">Мои книги</a>
                    </li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}

                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}?next={{request.path}}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
                    <li class="nav-item"><a class="nav-link"><span class="glyphicon glyphicon-log-in"></span> Hello, {{user.get_username}}</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={{request.path}}"><span class="glyphicon glyphicon-user fontawesome-lock"></span> Login</a></li>
                    {% endif %}
                </ul>
                <ul>
                    <li class="nav-item">
                        <a>Visits: {{num_visits}}{% if num_visits == 1%}time{% else %} times {% endif %}</a>
                    </li>
                </ul>


            </nav>
        </div>
        <h1>{% block page_name %} Мои книги {% endblock %}</h1>
       <h1>Просроченные</h1>
  {% if bookinstance_list %}
  <ul>
    {% for bookinst in bookinstance_list %}
    <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
      <a href="{% url 'detail' bookinst.book.pk %}">
        {{bookinst.book.title}}
      </a>({{bookinst.due_back}})
    </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books borrowed. </p>
  {% endif %}
</html>

auf/board/templates/detail.html
{% extends 'main_page.html'%}
{% block page_name %}
<h2>
    {{book.title}}
</h2>
{% endblock %}
{% block content %}
    <ul style="">
        <p>Жанр {{book.genre}}</p>
        <p>Год выпуска {{book.year}}</p>
        <p>Автор {{book.author}}</p>
        <p>Описание {{book.description}}</p>
        <p><img src='{{book.img.url}}' alt=""></p>
        <p>Цена {{book.price}}</p>
        <p>Состояние {{book.condition}}</p>
        <p class="price">${{book.price}}</p>
        <form action="#" method="post">
            {{cart_product_form}}
            {% csrf_token %}
            <input type="submit" value="Add to cart">
        </form>
    </ul>
</form>

{% endblock %}

auf/board/templates/genre_detail.html
{% extends 'main_page.html'%}
{% block page_name %}
<h2>
    {{genre.genre}}
</h2>
{% endblock %}
{% block content %}
    <h1>{{author.author}}</h1>
{% for book in books %}
{{book.title}}
<img src="{{book.img.url}}" alt="" height="" >
{% endfor %}

{% endblock %}

auf/board/templates/genres.html
{% extends 'main_page.html'%}

{% block content %}
{% for genre in genres %}
<a type="button" class="btn btn-light"  href="{% url 'genre_detail' genre.id %}">{{genre.genre}}<br></a>

{% endfor %}

{% endblock %}

auf/board/templates/main_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>{% block title%}STORE{% endblock%}</title>

</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <nav class="navbar navbar-expand bg-info navbar-dark navbar-fixed-top ">
                <a class="navbar-brand" href='/main_page/'}>Главная страница</a>
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="/authors/">Авторы</a>
                    </li>

                    <a class="nav-link" href="/genres/">Жанры</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/add/">Добавление книги</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/search/">Поиск</a>
                    </li>


                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}

                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}?next={{request.path}}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
                    <li class="nav-item"><a class="nav-link"><span class="glyphicon glyphicon-log-in"></span> Hello, {{user.get_username}}</a></li>
                    <li class="nav-item"><a class="nav-link" href="/mybooks/">Мои книги</a>
                    {% else %}
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={{request.path}}"><span class="glyphicon glyphicon-user fontawesome-lock"></span> Login</a></li>
                    {% endif %}
                </ul>
                <nav class="nav flex-column">
  <a class="nav-link active" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
  <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
  <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
</svg>{{num_visits}}{% if num_visits == 1%}time{% else %} times {% endif %}</a>
  <a class="nav-link" href="/cart/"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
</svg></i>Корзина</a>
</nav>


        </div>
        {% block page_name %}
            <div class="jumbotron">
  <h1 class="display-4">Итак</h1>
  <p class="lead">Разбираемся с агрегацией</p>
  <hr class="my-4">
  <p>Попробуем на практике все методы. Сделали свою комманду и создали 100 книг</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="/queryset/" role="button">Learn more</a>
  </p>
                <h1 class="display-4">Магазин</h1>
</div>{% endblock %}
        {%block content %}


        {% for book in books%}



        <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{book.img.url}}" alt="Card image cap" height="200">
  <div class="card-body">
    <h5 class="card-title">{{book.title}}</h5>
    <p class="card-text">{{book.description|truncatechars_html:150}}</p>
      <ul class="list-group list-group-flush">
    <li class="list-group-item">{{book.author}}</li>
    <li class="list-group-item">{{book.year}} год</li>
    <li class="list-group-item">{{book.price}}$</li>
  </ul>
    <a href="{% url 'detail' book.id %}" class="btn btn-primary">Смотреть подробнее</a>
  </div>
</div>
                  {% endfor %}
                {% endblock %}



                <ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link active" href="#">Active</a>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Таблица взаимосвязей</a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="/api/relation/">1</a>
      <a class="dropdown-item" href="2">Another action</a>
      <a class="dropdown-item" href="1">Something else here</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">Separated link</a>
    </div>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Disabled</a>
  </li>
</ul>
</body>
</html>

auf/board/templates/search.html
{% extends 'main_page.html'%}
{% block page_name %}
<h2>
    Страница поиска
</h2>
{% endblock %}
{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <h7>По названию:</h7>
    {{form.title}}
    <button>Gоиск</button>
</form>
{% for l in list%}
        <div class="container">
            <a href="{% url 'detail' l.id %}"><h3>{{l.title}}</h3></a>
            <div class="row align-items-start">
                <div class="col">
                    <img src='{{books.img.url}}' alt=""> <p>здесь будет картинка</p>
                </div>
            </div>
            <div class="row align-items-start">
                <div class="col">
                    {{l.author}}
                </div>
                <div class="col">
                    {{l.year}}
                </div>
                <div class="col">
                    {{l.price}}$
                </div>
                <div class="row align-items-start"><div class="col">{{l.description}}</div></div>
                {% endfor %}
{% endblock %}